name: Prettier
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Prettier
        run: yarn format:test
